name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: pop-os-1

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libssl-dev \
          libargon2-dev \
          nlohmann-json3-dev \
          pkg-config

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: build
      run: cmake ../cli

    - name: Build
      working-directory: build
      run: make -j$(nproc)

    - name: Check binary
      working-directory: build
      run: |
        ls -la localpdub-linux-x86_64
        file localpdub-linux-x86_64
        ldd localpdub-linux-x86_64 || true

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: localpdub-linux-x86_64-ci
        path: build/localpdub-linux-x86_64
        retention-days: 7